Fix start error in  load_persistent_executions (#759)
* Fix start error in  load_persistent_executions

Fix parse error that prevented Supervisor from starting when loading
persistant executions, as it could not parse the gpu field

    Traceback (most recent call last):
      File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/opt/aleph-vm/aleph/vm/orchestrator/__main__.py", line 4, in <module>
        main()
      File "/opt/aleph-vm/aleph/vm/orchestrator/cli.py", line 379, in main
        supervisor.run()
      File "/opt/aleph-vm/aleph/vm/orchestrator/supervisor.py", line 184, in run
        asyncio.run(pool.load_persistent_executions())
      File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
        return loop.run_until_complete(main)
      File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
        return future.result()
      File "/opt/aleph-vm/aleph/vm/pool.py", line 252, in load_persistent_executions
        execution.gpus = parse_raw_as(List[HostGPU], saved_execution.gpus)
      File "pydantic/tools.py", line 74, in pydantic.tools.parse_raw_as
        obj = load_str_bytes(
      File "pydantic/parse.py", line 37, in pydantic.parse.load_str_bytes
        return json_loads(b)
      File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
        raise TypeError(f'the JSON object must be str, bytes or bytearray, '
    TypeError: the JSON object must be str, bytes or bytearray, not NoneType

* Fix packaging issue caused by sevctl