Attempt to fix the packaging issue on Ubuntu 22.02
Error in CI https://github.com/aleph-im/aleph-vm/actions/runs/13458482852/job/37788353003

 pip3 install --progress-bar off --target ./aleph-vm/opt/aleph-vm/ 'aleph-message==0.6' 'eth-account==0.10' 'sentry-sdk==1.31.0' 'qmp==1.1.0' 'aleph-superfluid~=0.2.1' 'sqlalchemy[asyncio]>=2.0' 'aiosqlite==0.19.0' 'alembic==1.13.1' 'aiohttp_cors==0.7.0' 'pyroute2==0.7.12' 'python-cpuid==0.1.0' 'solathon==1.0.2' 'protobuf==5.28.3'
Collecting aleph-message==0.6
  Downloading aleph_message-0.6.0-py3-none-any.whl (17 kB)
Collecting eth-account==0.10
  Downloading eth_account-0.10.0-py3-none-any.whl (109 kB)
Collecting sentry-sdk==1.31.0
  Downloading sentry_sdk-1.31.0-py2.py3-none-any.whl (224 kB)
Collecting qmp==1.1.0
  Downloading qmp-1.1.0-py3-none-any.whl (11 kB)
Collecting aleph-superfluid~=0.2.1
  Downloading aleph_superfluid-0.2.1.tar.gz (20 kB)
  Preparing metadata (setup.py) ... 25l- done
25hCollecting sqlalchemy[asyncio]>=2.0
  Downloading SQLAlchemy-2.0.38-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting aiosqlite==0.19.0
  Downloading aiosqlite-0.19.0-py3-none-any.whl (15 kB)
Collecting alembic==1.13.1
  Downloading alembic-1.13.1-py3-none-any.whl (233 kB)
Collecting aiohttp_cors==0.7.0
  Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Collecting pyroute2==0.7.12
  Downloading pyroute2-0.7.12-py3-none-any.whl (460 kB)
Collecting python-cpuid==0.1.0
  Downloading python-cpuid-0.1.0.tar.gz (21 kB)
  Installing build dependencies ... 25l- \ | / - done
25h  Getting requirements to build wheel ... 25l- error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]

      An error occurred while building the project, please ensure you have the most updated version of setuptools, setuptools_scm and wheel with:
         pip install -U setuptools setuptools_scm wheel

      Traceback (most recent call last):
        File /usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py, line 363, in <module>
          main()
        File /usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py, line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File /usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py, line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File /usr/lib/python3/dist-packages/setuptools/build_meta.py, line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File /usr/lib/python3/dist-packages/setuptools/build_meta.py, line 143, in _get_build_requires
          self.run_setup()
        File /usr/lib/python3/dist-packages/setuptools/build_meta.py, line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File setup.py, line 18, in <module>
          setup(
        File /usr/lib/python3/dist-packages/setuptools/__init__.py, line 153, in setup
          return distutils.core.setup(**attrs)
        File /usr/lib/python3/dist-packages/setuptools/_distutils/core.py, line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File /usr/lib/python3/dist-packages/setuptools/dist.py, line 459, in __init__
          _Distribution.__init__(
        File /usr/lib/python3/dist-packages/setuptools/_distutils/dist.py, line 293, in __init__
          self.finalize_options()
        File /usr/lib/python3/dist-packages/setuptools/dist.py, line 836, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File /usr/lib/python3/dist-packages/setuptools/dist.py, line 835, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File /usr/lib/python3/dist-packages/pkg_resources/__init__.py, line 2464, in load
          self.require(*args, **kwargs)
        File /usr/lib/python3/dist-packages/pkg_resources/__init__.py, line 2487, in require
          items = working_set.resolve(reqs, env, installer, extras=self.extras)
        File /usr/lib/python3/dist-packages/pkg_resources/__init__.py, line 782, in resolve
          raise VersionConflict(dist, req).with_context(dependent_req)
      pkg_resources.VersionConflict: (setuptools 59.6.0 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=61'))
      [end of output]