Fix: Invalid ItemHash did not raise a ValidationError
Problem: Posting invalid item hashes to the `update_allocations` API failed far after the initial validation, with:

 ```   File "/opt/aleph-vm/aleph_message/models/item_hash.py", line 25, in from_hash
     raise UnknownHashError(f"Could not determine hash type: '{item_hash}'")
aleph_message.exceptions.UnknownHashError: Could not determine hash type: '${{ matrix.check_vm.item_hash }}'
```

Solution: Require ItemHash as part of the `Allocation` schema, in order to fail validation earlier, in the section dedicated to the validation of the uploaded data.