Fix is_confidential property (#674)
This was causing an error in the monitor payment task

AttributeError: 'FunctionEnvironment' object has no attribute 'trusted_execution'
  File "aleph/vm/utils/__init__.py", line 90, in run_and_log_exception
    return await coro
  File "aleph/vm/orchestrator/tasks.py", line 154, in monitor_payments
    executions = [execution for execution in executions if execution.is_confidential]
  File "aleph/vm/orchestrator/tasks.py", line 154, in <listcomp>
    executions = [execution for execution in executions if execution.is_confidential]
  File "aleph/vm/models.py", line 113, in is_confidential
    return True if self.message.environment.trusted_execution else False