Fix ALPEH-517 confidential clean up
ConfidentialQemuVM teardown was trying to close the journal stdout but
they were not properly set. (they are set properly in qemuvm)

```
python3[1738237]: 2025-04-14 13:41:13,531 | ERROR | Task exception was never retrieved
python3[1738237]: future: <Task finished name='Task-3' coro=<QemuVM.stop() done, defined at /opt/aleph-vm/aleph/vm/hypervisors/qemu/qemuvm.py:180> exception=AttributeError("'QemuConfidentialVM' object has no attribute 'journal>
python3[1738237]: Traceback (most recent call last):
python3[1738237]:   File "/opt/aleph-vm/aleph/vm/hypervisors/qemu/qemuvm.py", line 184, in stop
python3[1738237]:     if self.journal_stdout and self.journal_stdout != asyncio.subprocess.DEVNULL:
python3[1738237]:        ^^^^^^^^^^^^^^^^^^^
```