Problem: Vm execution failed due to network interface
occasionaly vm creation vm because the assigned tap network inteface was already existing. Probably not properly teared down from a previous execution or from a concurrency issue

Displayed Error was :
 OSError: [Errno 16] Device or resource busy

it was then looped as a retry and blocked the whole thing

Solution:
When assigning a vm_id, check that the network interface for that vm doesn't already exists
This act as a double check for a variety of issue