Problem: status_check_fastapi endpoint raising eror
Endpoint `/status/check/fastapi` was raising error when there was no
internet inside vm

This was caused by `check_internet` raising an error instead of just
returning False

Note: Contrarely to what was previously understood the diagnostic vm don't
return a headers when the result is False.

Previous stacktrace
```
ValueError: The server cannot connect to Internet
  File "aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
  File "aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "aleph/vm/orchestrator/supervisor.py", line 70, in server_version_middleware
    resp: web.StreamResponse = await handler(request)
  File "aleph/vm/orchestrator/views/__init__.py", line 215, in status_check_fastapi
    "internet": await status.check_internet(session, fastapi_vm_id),
  File "aleph/vm/orchestrator/status.py", line 124, in check_internet
    raise ValueError("The server cannot connect to Internet")
```

Sentry issue : https://alephim.sentry.io/issues/5654330290/