Problem: Vm execution failed due to network interface (#596)
Occasionally, VM creation failed because the assigned TAP network interface already existed, likely due to improper teardown from a previous execution or a concurrency issue.

Displayed Error:
OSError: [Errno 16] Device or resource busy

This caused a retry loop, blocking the process.

Solution:
When assigning a VM ID, check that the network interface for that VM doesn't already exist. This acts as a double check for various issues.