Fix: Kubo 33.2 crashed on Ubuntu 22.04
Due to an error reading the denylist.

The error was:
```
Error: constructing the node (see log for full detail):
error walking /home/ipfs/.config/ipfs/denylists:
lstat /home/ipfs/.config/ipfs/denylists: permission denied
```

The [documentation](https://specs.ipfs.tech/compact-denylist-format/)
mentions that:

> Implementations SHOULD look in /etc/ipfs/denylists/ and
> $XDG_CONFIG_HOME/ipfs/denylists/ (default: ~/.config/ipfs/denylists)
> for denylist files.

I am not sure why this only failed on Ubuntu 22.04
and not Debian 12 or Ubuntu 24.04. My first assumption
would be a difference in Systemd.