Fix: Logs of invalid messages were too verbose
This reduces the log level to warning and does not print the stacktrace.

We also add the `item_hash` in the logs for diagnostic as it was missing.

Previously, logs looked like:
```
2024-02-02 10:16:59,290 | ERROR | Invalid Aleph message:
  [
  {
    "loc": [
      "content",
      "payment"
    ],
    "msg": "extra fields not permitted",
    "type": "value_error.extra"
  }
]
  [ErrorWrapper(exc=ValidationError(model='InstanceContent', errors=[{'loc': ('payment',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}]), loc=('content',))]
Traceback (most recent call last):
  File "/opt/aleph-vm/aleph/vm/orchestrator/tasks.py", line 63, in subscribe_via_ws
    yield parse_message(data)
  File "/opt/aleph-vm/aleph_message/models/__init__.py", line 366, in parse_message
    return message_class.parse_obj(message_dict)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for InstanceMessage
content -> payment
  extra fields not permitted (type=value_error.extra)
```