Problem: sevctl installation broken on Ubuntu
sevctl 0.4.3 was refusing to compile on Ubuntu 22.04 and 24.02
because of some deps. This happened in the Github CI

This prevented the build of package and the testing inside the CI

Solution: Update sevctl to 0.6.0

Error logs
        Compiling structopt-derive v0.4.18
    error[E0658]: `c".."` literals are experimental
      --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kvm-ioctls-0.19.0/src/ioctls/system.rs:99:24
       |
    99 |         let kvm_path = c"/dev/kvm";
       |                        ^^^^^^^^^^^
       |
       = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information

    error[E0658]: `c".."` literals are experimental
       --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kvm-ioctls-0.19.0/src/ioctls/system.rs:744:24
        |
    744 |         let kvm_path = c"/dev/kvm";
        |                        ^^^^^^^^^^^
        |
        = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information

    For more information about this error, try `rustc --explain E0658`.
    The following warnings were emitted during compilation:

    warning: kvm-ioctls@0.19.0: cargo:rustc-check-cfg requires -Zcheck-cfg flag

    error: could not compile `kvm-ioctls` (lib) due to 2 previous errors
    warning: build failed, waiting for other jobs to finish...
    error: failed to compile `sevctl v0.4.3 (https://github.com/virtee/sevctl.git?rev=c41c9172be013d6f10b9e1d7286fcb021805d5a5#c41c9172)`, intermediate artifacts can be found at `/tmp/cargo-installXhERbT`.
    To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
    make: *** [Makefile:51: target/bin/sevctl] Error 101
    make: *** [Makefile:89: all-podman-ubuntu-2204] Error 2